# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ce0fa79cbb02ac54c86403279f05cc30893fb52c5dca8ea4e3c6e239dc7b8ae6f9ed2b32e9f7d7751693b9108566e2ce732304a7ca6589654f1acf999e23180

test:
  secret_key_base: d4ef765fb688ffc7b565627aed7dbe2c062b1bb97d357da789ef0cf2e7090a3e1dcd1ab6cd0facfd719e1c6b7d41ba985b8792bc3d8ccb029a39acee455f6cf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
